Repository kudobuilder/kuttl, pull requests merged in 2024-12, with the labels that each got.

#582 Bump go version to 1.22.7
  go.mod
Labels: dependencies

#583 Clarify help terminology
  pkg/kuttlctl/cmd/test.go
Labels: documentation, release/bugfix

#585 fix: lock testsuite and sort child testcases
  pkg/report/report.go
Labels: release/bugfix

#587 Allow for processing tls-server-name attribute in kubeconfig context
  pkg/test/utils/kubernetes.go
Labels: release/bugfix

#596 Bump go, k8s deps and linter versions, and some fixes
  .golangci.yml
  Makefile
  go.mod
  go.sum
  pkg/apis/apis.go
  pkg/apis/testharness/v1beta1/collector.go
  pkg/apis/testharness/v1beta1/collector_test.go
  pkg/apis/testharness/v1beta1/command_test.go
  pkg/apis/testharness/v1beta1/doc.go
  pkg/apis/testharness/v1beta1/test_types.go
  pkg/env/env_test.go
  pkg/file/files_test.go
  pkg/http/client.go
  pkg/http/http_test.go
  pkg/kubernetes/object_test.go
  pkg/kubernetes/retry_client.go
  pkg/kubernetes/retry_client_integration_test.go
  pkg/kubernetes/retry_client_test.go
  pkg/kubernetes/serialization_test.go
  pkg/kuttlctl/cmd/assert.go
  pkg/kuttlctl/cmd/errors.go
  pkg/kuttlctl/cmd/test.go
  pkg/kuttlctl/cmd/values.go
  pkg/report/report.go
  pkg/report/report_test.go
  pkg/test/case_test.go
  pkg/test/harness.go
  pkg/test/kind_test.go
  pkg/test/step.go
  pkg/test/step_integration_test.go
  pkg/test/step_test.go
  pkg/test/utils/commands_test.go
  pkg/test/utils/subset.go
  pkg/version/version_test.go
Labels: dependencies
